# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='voter_name',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Имя'),
        ),
    ]
